spring.application.name=CareAssist

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/careassist
spring.datasource.username=careassist_user
spring.datasource.password=CareAssist@2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

logging.file.name=logs/careassist.log
logging.level.root=INFO
logging.level.com.hexaware.careassist=DEBUG

# JWT
jwt.secret=CareAssistSecretKeyForJwtAuthentication2026HexawareProject
jwt.expiration=86400000

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dineshsiva.dk29@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Frontend URL
app.frontend.url=http://careassist-frontend-hexa.s3-website.ap-south-2.amazonaws.com

# Allowed CORS Origin
app.cors.allowed-origin=http://careassist-frontend-hexa.s3-website.ap-south-2.amazonaws.com