import { useEffect, useState } from "react";
import { getPatientInvoices } from "../../services/patient/patientService";

function Invoice() {

    const [invoices, setInvoices] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");

    useEffect(() => {
        loadInvoices();
    }, []);

    const loadInvoices = async () => {

        try {

            setLoading(true);
            setError("");

            const patientId = localStorage.getItem("patientId");

            const data = await getPatientInvoices(patientId);

            setInvoices(data);

        }
        catch (err) {

            console.error(err);

            setError("Unable to load invoices. Please try again.");

        }
        finally {

            setLoading(false);

        }

    };

    return (

        <div className="container mt-4">

            <div className="mb-4">

                <h2 className="fw-bold">
                    My Invoices
                </h2>

                <p className="text-muted mb-0">
                    View all invoices generated by your healthcare provider.
                </p>

            </div>

            {
                error &&
                <div className="alert alert-danger">
                    {error}
                </div>
            }

            {
                loading ? (

                    <div className="text-center my-5">

                        <div
                            className="spinner-border text-primary"
                            role="status"
                        >
                            <span className="visually-hidden">
                                Loading...
                            </span>
                        </div>

                        <p className="mt-3">
                            Loading invoices...
                        </p>

                    </div>

                ) : (

                    <div className="card shadow-sm">

                        <div className="card-body">

                            <div className="table-responsive">

                                <table className="table table-hover align-middle">

                                    <thead className="table-dark">

                                        <tr>
                                            <th>Invoice No</th>
                                            <th>Invoice Date</th>
                                            <th>Due Date</th>
                                            <th>Total Amount</th>
                                            <th>Status</th>
                                        </tr>

                                    </thead>

                                    <tbody>

                                        {

                                            invoices.length > 0 ? (

                                                invoices.map((invoice) => (

                                                    <tr key={invoice.invoiceId}>

                                                        <td className="fw-semibold">
                                                            {invoice.invoiceNumber}
                                                        </td>

                                                        <td>
                                                            {new Date(invoice.invoiceDate).toLocaleDateString()}
                                                        </td>

                                                        <td>
                                                            {new Date(invoice.dueDate).toLocaleDateString()}
                                                        </td>

                                                        <td>
                                                            ₹{Number(invoice.totalAmount).toLocaleString()}
                                                        </td>

                                                        <td>

                                                            <span
                                                                className={`badge ${
                                                                    invoice.status === "PAID"
                                                                        ? "bg-success"
                                                                        : "bg-warning text-dark"
                                                                }`}
                                                            >
                                                                {invoice.status}
                                                            </span>

                                                        </td>

                                                    </tr>

                                                ))

                                            ) : (

                                                <tr>

                                                    <td
                                                        colSpan="5"
                                                        className="text-center py-4 text-muted"
                                                    >
                                                        No invoices found.
                                                    </td>

                                                </tr>

                                            )

                                        }

                                    </tbody>

                                </table>

                            </div>

                        </div>

                    </div>

                )

            }

        </div>

    );

}

export default Invoice;